
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    pwd VARCHAR(256),
    pwd_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    token_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    role VARCHAR(32) NOT NULL DEFAULT 'user'

);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES "user"(id)
);

CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    filename VARCHAR(256) NOT NULL,
    filepath VARCHAR(512) NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES "user"(id)
);

create table conversation (
                              id           bigserial primary key,
                              owner_id     bigint  not null references "user"(id) on delete cascade,
                              title        text    not null default 'Untitled chat',
                              created_at   timestamptz default now(),
                              updated_at   timestamptz default now()
);

create table message (
                         id              bigserial primary key,
                         conversation_id bigint  not null references conversation(id) on delete cascade,
                         sender          text    not null check (sender in ('user','assistant')),
                         content         text    not null,
                         token_count     int     not null,
                         created_at      timestamptz default now()
);

create index on message(conversation_id, id);

CREATE TABLE pipeline_log (
                              id               BIGSERIAL PRIMARY KEY,
                              user_id          BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
                              pipeline         TEXT    NOT NULL,
                              duration_ms      INTEGER NOT NULL,
                              created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX ON pipeline_log(created_at);